### ISSUE TITLE
Error when opening first "Surround With" context menu

### ISSUE THREAD

**Issue by ghost** [Nightro/VSBlockJumper#1]
Error when opening first "Surround With" context menu (CTRL + K + S). It just shows up first time.

![snipaste20170728_204442](https://user-images.githubusercontent.com/25173234/28714162-9c27177a-73d5-11e7-81dc-feaff0c00dde.jpg)

**Comment by Nightro** [comment]
Thanks for this! I'll look into it, sorry for the delay in response - I somehow never received a notification. On it!

**Comment by Nightro** [comment]
Didn't actually mean to close!
