### ISSUE TITLE
VS2022 Support

### ISSUE THREAD

**Issue by obsgolem** [Nightro/VSBlockJumper#3]
I tried migrating this to VS2022 myself, but found that it is a bit of an ordeal, especially for someone without any familiarity with C#.

**Comment by Nightro** [comment]
Hi there, I finally spent some time to migrate this to VS2022. I didn't bother keeping a project to support the older editions, but the version 1.1.4 is tagged and was the last version to support older version of VS should we need to go back to the code.

You can search in VS marketplace now and find the new edition of the extension. Sorry for the long long wait.

**Comment by Nightro** [comment]
This has been fixed with v1.1.5
